name: Metrics
on:
  # Se ejecuta a medianoche
  schedule: [{cron: "0 0 * * *"}]
  # Se ejecuta si haces push a main/master
  push: {branches: ["master", "main"]}
  # Permite ejecutarlo manualmente
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configuración básica
          user: mauri101-Ar
          template: classic
          base: "" # No queremos info basica, solo lenguajes
          config_timezone: America/Argentina/Buenos_Aires
          
          # Configuración de Lenguajes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          
          # Archivo de salida
          filename: github-metrics.svg
